spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authDB?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    datasource:
      initialization-mode: always
        tomcat:
          initial-size: 10
          max-wait: 120000
          max-active: 50
          max-idle: 15
          min-idle: 8
          default-auto-commit: true
          test-on-borrow: true
          validation-query: SELECT 1
          test-while-idle: true
          remove-abandoned: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
        javax:
          persistence:
            sharedCache:
              mode: ENABLE_SELECTIVE
logging:
  level:
    org:
      hibernate:
        type: trace
